# Site settings
title: Zhaobo Liu
email: liuzhaobo@szu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  I'm a assistant professor at Shenzhen University with research interests in
  control theory, data science, and computational intelligence. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://liuzhaobo-site.github.io/" # the base hostname & protocol for your site
github_username:  liuzhaobo-site
orcid_id: 0000-0003-3140-668X


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff



plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
